### ISSUE TITLE
Default support for Map and Set would be nice :-)

### ISSUE THREAD

**Issue by core-process** [fdc-viktor-luft/serialize-as-code#1]
(Solved it via Custom extension for now)

**Comment by fdc-viktor-luft** [comment]
Sounds reasonable to me. Coming soon. :v:

**Comment by fdc-viktor-luft** [comment]
Resolved :+1: See here: https://github.com/fdc-viktor-luft/serialize-as-code/releases/tag/v1.1.0

**Comment by core-process** [comment]
@fdc-viktor-luft  Awesome, thanks!!!
